In [2]:
import requests
import pandas as pd

In [3]:
API_URL = "https://clinicaltrials.gov/api/v2/studies"

params = {
    "query.cond": "Endometriosis",
    "pageSize": 5,
    "format": "json"
}

response = requests.get(API_URL, params=params, timeout=30)

print(response.status_code)

200

In [4]:
data = response.json()

data.keys()

dict_keys(['studies', 'nextPageToken'])

In [5]:
len(data["studies"])

5

In [6]:
data["studies"][0]

{'protocolSection': {'identificationModule': {'nctId': 'NCT06495151',
   'orgStudyIdInfo': {'id': 'E2-22-1998'},
   'organization': {'fullName': 'Ankara City Hospital Bilkent',
    'class': 'OTHER'},
   'briefTitle': 'Endometriosis and Complement System',
   'officialTitle': 'Evaluation of Serum and Peritoneal Fluid Mannose-binding Lectin Associated Serine Protease-3, Adipsin, Properdin, and Complement Factor H Levels in Endometriosis Patients'},
  'statusModule': {'statusVerifiedDate': '2024-07',
   'overallStatus': 'COMPLETED',
   'expandedAccessInfo': {'hasExpandedAccess': False},
   'startDateStruct': {'date': '2022-06-10', 'type': 'ACTUAL'},
   'primaryCompletionDateStruct': {'date': '2022-09-12', 'type': 'ACTUAL'},
   'completionDateStruct': {'date': '2022-10-07', 'type': 'ACTUAL'},
   'studyFirstSubmitDate': '2024-07-03',
   'studyFirstSubmitQcDate': '2024-07-03',
   'studyFirstPostDateStruct': {'date': '2024-07-10', 'type': 'ACTUAL'},
   'lastUpdateSubmitDate': '2024-07-11',
   'lastUpdatePostDateStruct': {'date': '2024-07-12', 'type': 'ACTUAL'}},
  'sponsorCollaboratorsModule': {'responsibleParty': {'type': 'PRINCIPAL_INVESTIGATOR',
    'investigatorFullName': 'Merve Didem Eşkin Tanrıverdi',
    'investigatorTitle': 'Medical Doctor',
    'investigatorAffiliation': 'Ankara City Hospital Bilkent'},
   'leadSponsor': {'name': 'Ankara City Hospital Bilkent', 'class': 'OTHER'}},
  'oversightModule': {'oversightHasDmc': False,
   'isFdaRegulatedDrug': False,
   'isFdaRegulatedDevice': False},
  'descriptionModule': {'briefSummary': 'Endometriosis is a chronic gynecological condition affecting nearly 10% of women of reproductive age. A definitive diagnosis of endometriosis requires laparoscopy. Studies aim to identify novel biomarkers to aid in the development of effective noninvasive diagnostic methods. Despite several theories, the full understanding of the etiopathogenesis remains elusive. A distorted immune response is thought to play a crucial role in the pathophysiology of endometriosis. This study aimed to evaluate whether the levels of alternative complement molecules change in the blood serum and peritoneal fluid of endometriosis patients compared to healthy subjects.',
   'detailedDescription': 'Endometriosis is a chronic gynecological condition affecting nearly 10% of women of reproductive age. It has been reported to contribute to 21-47% of cases of female infertility and 71-87% of cases involving chronic pelvic pain. The definitive diagnosis of endometriosis requires laparoscopy. While CA-125 has diagnostic value, it is not specific to endometriosis. Therefore, studies are focused on identifying novel biomarkers to aid in the development of effective noninvasive diagnostic methods. Despite numerous theories, the etiopathogenesis of endometriosis remains incompletely understood. A distorted immune response is believed to play a crucial role in the pathophysiology of the condition. Regarding alterations in the classical and lectin-dependent complement systems, C3a, C3c, C4, and C5b-9 have been suggested to hold potential diagnostic value in endometriosis. Alternative pathway is another way for complement activation. This study aimed to investigate whether there are alterations in the levels of alternative complement molecules in both the blood serum and peritoneal fluid of patients diagnosed with endometriosis, comparing these levels to those found in healthy individuals. The research focused on understanding potential differences that could contribute to the pathophysiology of endometriosis, aiming to provide insights into the role of the alternative complement pathway in this gynecological condition.'},
  'conditionsModule': {'conditions': ['Endometriosis',
    'Complement System',
    'Alternative Complement Pathway']},
  'designModule': {'studyType': 'OBSERVATIONAL',
   'patientRegistry': False,
   'designInfo': {'observationalModel': 'CASE_CONTROL',
    'timePerspective': 'PROSPECTIVE'},
   'bioSpec': {'retention': 'SAMPLES_WITHOUT_DNA',
    'description': 'Serum samples were collected via antecubital venous blood sampling. In the study group, serum samples were obtained just before laparoscopy, while peritoneal fluid (PF) samples were collected from the Douglas pouch at the time of trochar insertion into the abdominal cavity. Serum and PF MASP-3, adipsin, properdin, and CFH levels were evaluated.'},
   'enrollmentInfo': {'count': 58, 'type': 'ACTUAL'}},
  'armsInterventionsModule': {'armGroups': [{'label': 'Endometriosis group (Study group)',
     'description': '* The study group included 32 women with endometriosis.\n* The study group consisted of women diagnosed with endometriosis who consecutively underwent laparoscopic endometriosis surgery.',
     'interventionNames': ['Diagnostic Test: Mannose-binding lectin-associated serine protease-3 (MASP-3) Level',
      'Diagnostic Test: Adipsin Level',
      'Diagnostic Test: Properdin Level',
      'Diagnostic Test: Complement Factor H (CFH) Level',
      'Diagnostic Test: Cancer Antigen 125 (CA-125) Level']},
    {'label': 'Healthy women (Control group)',
     'description': '* Control group consisted of 26 healthy women.\n* The control group consisted of women who consecutively visited the outpatient clinic for routine gynecologic examinations and had no known diseases.',
     'interventionNames': ['Diagnostic Test: Mannose-binding lectin-associated serine protease-3 (MASP-3) Level',
      'Diagnostic Test: Adipsin Level',
      'Diagnostic Test: Properdin Level',
      'Diagnostic Test: Complement Factor H (CFH) Level',
      'Diagnostic Test: Cancer Antigen 125 (CA-125) Level']}],
   'interventions': [{'type': 'DIAGNOSTIC_TEST',
     'name': 'Mannose-binding lectin-associated serine protease-3 (MASP-3) Level',
     'description': 'Measurement of venous blood serum and peritoneal fluid levels of MASP-3 level by ELISA method.',
     'armGroupLabels': ['Endometriosis group (Study group)',
      'Healthy women (Control group)']},
    {'type': 'DIAGNOSTIC_TEST',
     'name': 'Adipsin Level',
     'description': 'Measurement of venous blood serum and peritoneal fluid levels of adipsin level by ELISA method.',
     'armGroupLabels': ['Endometriosis group (Study group)',
      'Healthy women (Control group)']},
    {'type': 'DIAGNOSTIC_TEST',
     'name': 'Properdin Level',
     'description': 'Measurement of venous blood serum and peritoneal fluid levels of properdin level by ELISA method.',
     'armGroupLabels': ['Endometriosis group (Study group)',
      'Healthy women (Control group)']},
    {'type': 'DIAGNOSTIC_TEST',
     'name': 'Complement Factor H (CFH) Level',
     'description': 'Measurement of venous blood serum and peritoneal fluid levels of CFH level by ELISA method.',
     'armGroupLabels': ['Endometriosis group (Study group)',
      'Healthy women (Control group)']},
    {'type': 'DIAGNOSTIC_TEST',
     'name': 'Cancer Antigen 125 (CA-125) Level',
     'description': 'Measurement of venous blood serum level of CA-125 level by ELISA method.',
     'armGroupLabels': ['Endometriosis group (Study group)',
      'Healthy women (Control group)']}]},
  'outcomesModule': {'primaryOutcomes': [{'measure': 'Serum and peritoneal fluid mannose-binding lectin-associated serine protease-3 level',
     'description': 'Nanogram/milliliter',
     'timeFrame': 'day 1'},
    {'measure': 'Serum and peritoneal fluid adipsin level',
     'description': 'Nanogram/milliliter',
     'timeFrame': 'day 1'},
    {'measure': 'Serum and peritoneal fluid properdin level',
     'description': 'Nanogram/milliliter',
     'timeFrame': 'day 1'},
    {'measure': 'Serum and peritoneal fluid complement factor H level',
     'description': 'Nanogram/milliliter',
     'timeFrame': 'day 1'}],
   'secondaryOutcomes': [{'measure': 'Serum cancer antigen 125 level',
     'description': 'Unit/milliliter',
     'timeFrame': 'day 1'}]},
  'eligibilityModule': {'eligibilityCriteria': "Inclusion Criteria:\n\n* Diagnosis of endometriosis for study group who underwent laparoscopic endometriosis surgery\n* Healthy women for control group\n\nExclusion Criteria:\n\n* Cardiovascular diseases including hypertension\n* Type 1 or type 2 diabetes mellitus\n* Morbid obesity\n* Primary adrenal insufficiency\n* Uterine fibroids\n* Thyroid dysfunctions including Hashimoto thyroiditis and Grave's disease\n* Hepatic dysfunctions\n* Renal insufficiency\n* Genetic disorders in chromosome constitution or karyotype analysis including monosomy X, trisomy X and gene mutations as BMP15, FMR I, POFIB, and GDF9\n* Neurologic diseases\n* Psychiatric disorders\n* Autoimmune diseases or syndromes including Addison's disease, autoimmune syndromes, scleroderma, Sjogren's syndrome, myasthenia gravis, inflammatory bowel diseases, multiple sclerosis, rheumatoid arthritis, systemic lupus erythematosus and familial Mediterranean fever\n* History of any malignancy\n* History of exposure to chemotherapeutic agents or radiotherapy",
   'healthyVolunteers': True,
   'sex': 'FEMALE',
   'genderBased': True,
   'genderDescription': 'Endometriosis is the presence of endometrial tissue outside the uterus, such as in the ovaries, fallopian tubes, peritoneal membrane, or abdominal cavity, and it is diagnosed exclusively in females.',
   'minimumAge': '18 Years',
   'maximumAge': '44 Years',
   'stdAges': ['ADULT'],
   'studyPopulation': 'Study population includes a total of 58 participants. The study group consists of 32 women with the diagnosis of endometriosis, and the control group consists of 26 healthy women.',
   'samplingMethod': 'NON_PROBABILITY_SAMPLE'},
  'contactsLocationsModule': {'overallOfficials': [{'name': 'Merve Didem Eşkin Tanrıverdi, MD',
     'affiliation': 'Ankara City Hospital Bilkent',
     'role': 'PRINCIPAL_INVESTIGATOR'}],
   'locations': [{'facility': 'Ankara Bilkent City Hospital',
     'city': 'Ankara',
     'zip': '06100',
     'country': 'Turkey (Türkiye)',
     'geoPoint': {'lat': 39.91987, 'lon': 32.85427}}]},
  'referencesModule': {'references': [{'pmid': '29420391',
     'type': 'BACKGROUND',
     'citation': 'Falcone T, Flyckt R. Clinical Management of Endometriosis. Obstet Gynecol. 2018 Mar;131(3):557-571. doi: 10.1097/AOG.0000000000002469.'},
    {'pmid': '31488888',
     'type': 'BACKGROUND',
     'citation': 'Chapron C, Marcellin L, Borghese B, Santulli P. Rethinking mechanisms, diagnosis and management of endometriosis. Nat Rev Endocrinol. 2019 Nov;15(11):666-682. doi: 10.1038/s41574-019-0245-z. Epub 2019 Sep 5.'},
    {'pmid': '32325082',
     'type': 'BACKGROUND',
     'citation': 'Karadadas E, Hortu I, Ak H, Ergenoglu AM, Karadadas N, Aydin HH. Evaluation of complement system proteins C3a, C5a and C6 in patients of endometriosis. Clin Biochem. 2020 Jul;81:15-19. doi: 10.1016/j.clinbiochem.2020.04.005. Epub 2020 Apr 20.'},
    {'pmid': '17482181',
     'type': 'BACKGROUND',
     'citation': 'Kabut J, Kondera-Anasz Z, Sikora J, Mielczarek-Palacz A. Levels of complement components iC3b, C3c, C4, and SC5b-9 in peritoneal fluid and serum of infertile women with endometriosis. Fertil Steril. 2007 Nov;88(5):1298-303. doi: 10.1016/j.fertnstert.2006.12.061. Epub 2007 May 4.'},
    {'pmid': '11724962',
     'type': 'BACKGROUND',
     'citation': 'Xu Y, Ma M, Ippolito GC, Schroeder HW Jr, Carroll MC, Volanakis JE. Complement activation in factor D-deficient mice. Proc Natl Acad Sci U S A. 2001 Dec 4;98(25):14577-82. doi: 10.1073/pnas.261428398. Epub 2001 Nov 27.'},
    {'pmid': '20720586',
     'type': 'BACKGROUND',
     'citation': 'Ricklin D, Hajishengallis G, Yang K, Lambris JD. Complement: a key system for immune surveillance and homeostasis. Nat Immunol. 2010 Sep;11(9):785-97. doi: 10.1038/ni.1923. Epub 2010 Aug 19.'},
    {'pmid': '34682837',
     'type': 'BACKGROUND',
     'citation': 'Poppelaars F, Faria B, Schwaeble W, Daha MR. The Contribution of Complement to the Pathogenesis of IgA Nephropathy: Are Complement-Targeted Therapies Moving from Rare Disorders to More Common Diseases? J Clin Med. 2021 Oct 14;10(20):4715. doi: 10.3390/jcm10204715.'},
    {'pmid': '34671343',
     'type': 'BACKGROUND',
     'citation': 'Liu M, Luo X, Xu Q, Yu H, Gao L, Zhou R, Wang T. Adipsin of the Alternative Complement Pathway Is a Potential Predictor for Preeclampsia in Early Pregnancy. Front Immunol. 2021 Oct 4;12:702385. doi: 10.3389/fimmu.2021.702385. eCollection 2021.'},
    {'pmid': '27434652',
     'type': 'BACKGROUND',
     'citation': 'Gursoy Calan O, Calan M, Yesil Senses P, Unal Kocabas G, Ozden E, Sari KR, Kocar M, Imamoglu C, Senses YM, Bozkaya G, Bilgir O. Increased adipsin is associated with carotid intima media thickness and metabolic disturbances in polycystic ovary syndrome. Clin Endocrinol (Oxf). 2016 Dec;85(6):910-917. doi: 10.1111/cen.13157. Epub 2016 Aug 15.'},
    {'pmid': '34696714',
     'type': 'BACKGROUND',
     'citation': 'Zhang J, Teng F, Pan L, Guo D, Liu J, Li K, Yuan Y, Li W, Zhang H. Circulating adipsin is associated with asymptomatic carotid atherosclerosis in obese adults. BMC Cardiovasc Disord. 2021 Oct 25;21(1):517. doi: 10.1186/s12872-021-02329-3.'},
    {'pmid': '34566967',
     'type': 'BACKGROUND',
     'citation': 'Barratt J, Weitz I. Complement Factor D as a Strategic Target for Regulating the Alternative Complement Pathway. Front Immunol. 2021 Sep 9;12:712572. doi: 10.3389/fimmu.2021.712572. eCollection 2021.'},
    {'pmid': '38145036',
     'type': 'BACKGROUND',
     'citation': 'Lei X, Song X, Fan Y, Chen Z, Zhang L. The Role and Potential Mechanism of Complement Factor D in Fibromyalgia Development. J Pain Res. 2023 Dec 19;16:4337-4351. doi: 10.2147/JPR.S439689. eCollection 2023.'},
    {'pmid': '33505394',
     'type': 'BACKGROUND',
     'citation': 'Agostinis C, Balduit A, Mangogna A, Zito G, Romano F, Ricci G, Kishore U, Bulla R. Immunological Basis of the Endometriosis: The Complement System as a Potential Therapeutic Target. Front Immunol. 2021 Jan 11;11:599117. doi: 10.3389/fimmu.2020.599117. eCollection 2020.'},
    {'pmid': '37108664',
     'type': 'BACKGROUND',
     'citation': 'Chen LH, Lo WC, Huang HY, Wu HM. A Lifelong Impact on Endometriosis: Pathophysiology and Pharmacological Treatment. Int J Mol Sci. 2023 Apr 19;24(8):7503. doi: 10.3390/ijms24087503.'},
    {'pmid': '27782323',
     'type': 'BACKGROUND',
     'citation': 'Garred P, Genster N, Pilely K, Bayarri-Olmos R, Rosbjerg A, Ma YJ, Skjoedt MO. A journey through the lectin pathway of complement-MBL and beyond. Immunol Rev. 2016 Nov;274(1):74-97. doi: 10.1111/imr.12468.'}]},
  'ipdSharingStatementModule': {'ipdSharing': 'NO',
   'description': 'IPD are available which may be shared in necessary conditions.'}},
 'derivedSection': {'miscInfoModule': {'versionHolder': '2026-08-11'},
  'conditionBrowseModule': {'meshes': [{'id': 'D004715',
     'term': 'Endometriosis'}],
   'ancestors': [{'id': 'D005831', 'term': 'Genital Diseases, Female'},
    {'id': 'D052776', 'term': 'Female Urogenital Diseases'},
    {'id': 'D005261',
     'term': 'Female Urogenital Diseases and Pregnancy Complications'},
    {'id': 'D000091642', 'term': 'Urogenital Diseases'},
    {'id': 'D000091662', 'term': 'Genital Diseases'}]}},
 'hasResults': False}

In [7]:
first_study = data["studies"][0]

protocol = first_study["protocolSection"]
protocol.keys()

dict_keys(['identificationModule', 'statusModule', 'sponsorCollaboratorsModule', 'oversightModule', 'descriptionModule', 'conditionsModule', 'designModule', 'armsInterventionsModule', 'outcomesModule', 'eligibilityModule', 'contactsLocationsModule', 'referencesModule', 'ipdSharingStatementModule'])

In [8]:
identification = protocol["identificationModule"]

print("NCT ID:", identification["nctId"])
print("Title:", identification["briefTitle"])

NCT ID: NCT06495151
Title: Endometriosis and Complement System

In [9]:
conditions = protocol.get("conditionsModule", {}).get("conditions", [])

print(conditions)

['Endometriosis', 'Complement System', 'Alternative Complement Pathway']

In [10]:
def extract_basic_study_info(study: dict, searched_condition: str) -> dict:
    """Extract selected fields from one ClinicalTrials.gov study record."""

    protocol = study.get("protocolSection", {})

    identification = protocol.get("identificationModule", {})
    status = protocol.get("statusModule", {})
    design = protocol.get("designModule", {})
    conditions = protocol.get("conditionsModule", {})
    sponsor = protocol.get("sponsorCollaboratorsModule", {})
    eligibility = protocol.get("eligibilityModule", {})

    enrollment_info = design.get("enrollmentInfo", {})
    lead_sponsor = sponsor.get("leadSponsor", {})

    return {
        "nct_id": identification.get("nctId"),
        "searched_condition": searched_condition,
        "brief_title": identification.get("briefTitle"),
        "listed_conditions": conditions.get("conditions", []),
        "study_type": design.get("studyType"),
        "overall_status": status.get("overallStatus"),
        "enrollment": enrollment_info.get("count"),
        "enrollment_type": enrollment_info.get("type"),
        "lead_sponsor": lead_sponsor.get("name"),
        "sponsor_class": lead_sponsor.get("class"),
        "sex": eligibility.get("sex"),
        "has_results": study.get("hasResults", False),
    }

In [11]:
records = [
    extract_basic_study_info(
        study=study,
        searched_condition="Endometriosis"
    )
    for study in data["studies"]
]

sample_df = pd.DataFrame(records)

sample_df

,nct_id,searched_condition,brief_title,listed_conditions,study_type,overall_status,enrollment,enrollment_type,lead_sponsor,sponsor_class,sex,has_results
0,NCT06495151,Endometriosis,Endometriosis and Complement System,"[Endometriosis, Complement System, Alternative...",OBSERVATIONAL,COMPLETED,58,ACTUAL,Ankara City Hospital Bilkent,OTHER,FEMALE,False
1,NCT05312528,Endometriosis,Evaluation of New Biomarkers in Stage 3 and 4 ...,[Endometriosis],OBSERVATIONAL,COMPLETED,79,ACTUAL,Bagcilar Training and Research Hospital,OTHER_GOV,FEMALE,False
2,NCT07664956,Endometriosis,Cyclobenzaprine for Postoperative Pain in Mini...,"[Minimally Invasive Surgical Procedures, Abnor...",INTERVENTIONAL,NOT_YET_RECRUITING,36,ESTIMATED,Christiana Care Health Services,OTHER,FEMALE,False
3,NCT04265781,Endometriosis,Study on the Safety of Drug BAY1817080 at Diff...,"[Endometriosis Related Pain, Overactive Bladde...",INTERVENTIONAL,COMPLETED,36,ACTUAL,Bayer,INDUSTRY,MALE,False
4,NCT07241637,Endometriosis,"Effect of Tele-Yoga on Pain, Fatigue, and Qual...","[Pelvic Pain, Endometriosis]",INTERVENTIONAL,COMPLETED,60,ACTUAL,Ankara University,OTHER,FEMALE,False

In [12]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   nct_id              5 non-null      object
 1   searched_condition  5 non-null      object
 2   brief_title         5 non-null      object
 3   listed_conditions   5 non-null      object
 4   study_type          5 non-null      object
 5   overall_status      5 non-null      object
 6   enrollment          5 non-null      int64
 7   enrollment_type     5 non-null      object
 8   lead_sponsor        5 non-null      object
 9   sponsor_class       5 non-null      object
 10  sex                 5 non-null      object
 11  has_results         5 non-null      bool
dtypes: bool(1), int64(1), object(10)
memory usage: 573.0+ bytes

In [13]:
sample_df[
    [
        "nct_id",
        "searched_condition",
        "study_type",
        "overall_status",
        "enrollment",
        "has_results"
    ]
]

,nct_id,searched_condition,study_type,overall_status,enrollment,has_results
0,NCT06495151,Endometriosis,OBSERVATIONAL,COMPLETED,58,False
1,NCT05312528,Endometriosis,OBSERVATIONAL,COMPLETED,79,False
2,NCT07664956,Endometriosis,INTERVENTIONAL,NOT_YET_RECRUITING,36,False
3,NCT04265781,Endometriosis,INTERVENTIONAL,COMPLETED,36,False
4,NCT07241637,Endometriosis,INTERVENTIONAL,COMPLETED,60,False

In [14]:
sample_df.to_csv(
    "../data/raw/endometriosis_sample.csv",
    index=False
)

In [15]:
data = response.json()

data.keys()

dict_keys(['studies', 'nextPageToken'])

In [16]:
len(data["studies"])

5

In [17]:
first_study = data["studies"][0]

first_study

{'protocolSection': {'identificationModule': {'nctId': 'NCT06495151',
   'orgStudyIdInfo': {'id': 'E2-22-1998'},
   'organization': {'fullName': 'Ankara City Hospital Bilkent',
    'class': 'OTHER'},
   'briefTitle': 'Endometriosis and Complement System',
   'officialTitle': 'Evaluation of Serum and Peritoneal Fluid Mannose-binding Lectin Associated Serine Protease-3, Adipsin, Properdin, and Complement Factor H Levels in Endometriosis Patients'},
  'statusModule': {'statusVerifiedDate': '2024-07',
   'overallStatus': 'COMPLETED',
   'expandedAccessInfo': {'hasExpandedAccess': False},
   'startDateStruct': {'date': '2022-06-10', 'type': 'ACTUAL'},
   'primaryCompletionDateStruct': {'date': '2022-09-12', 'type': 'ACTUAL'},
   'completionDateStruct': {'date': '2022-10-07', 'type': 'ACTUAL'},
   'studyFirstSubmitDate': '2024-07-03',
   'studyFirstSubmitQcDate': '2024-07-03',
   'studyFirstPostDateStruct': {'date': '2024-07-10', 'type': 'ACTUAL'},
   'lastUpdateSubmitDate': '2024-07-11',
   'lastUpdatePostDateStruct': {'date': '2024-07-12', 'type': 'ACTUAL'}},
  'sponsorCollaboratorsModule': {'responsibleParty': {'type': 'PRINCIPAL_INVESTIGATOR',
    'investigatorFullName': 'Merve Didem Eşkin Tanrıverdi',
    'investigatorTitle': 'Medical Doctor',
    'investigatorAffiliation': 'Ankara City Hospital Bilkent'},
   'leadSponsor': {'name': 'Ankara City Hospital Bilkent', 'class': 'OTHER'}},
  'oversightModule': {'oversightHasDmc': False,
   'isFdaRegulatedDrug': False,
   'isFdaRegulatedDevice': False},
  'descriptionModule': {'briefSummary': 'Endometriosis is a chronic gynecological condition affecting nearly 10% of women of reproductive age. A definitive diagnosis of endometriosis requires laparoscopy. Studies aim to identify novel biomarkers to aid in the development of effective noninvasive diagnostic methods. Despite several theories, the full understanding of the etiopathogenesis remains elusive. A distorted immune response is thought to play a crucial role in the pathophysiology of endometriosis. This study aimed to evaluate whether the levels of alternative complement molecules change in the blood serum and peritoneal fluid of endometriosis patients compared to healthy subjects.',
   'detailedDescription': 'Endometriosis is a chronic gynecological condition affecting nearly 10% of women of reproductive age. It has been reported to contribute to 21-47% of cases of female infertility and 71-87% of cases involving chronic pelvic pain. The definitive diagnosis of endometriosis requires laparoscopy. While CA-125 has diagnostic value, it is not specific to endometriosis. Therefore, studies are focused on identifying novel biomarkers to aid in the development of effective noninvasive diagnostic methods. Despite numerous theories, the etiopathogenesis of endometriosis remains incompletely understood. A distorted immune response is believed to play a crucial role in the pathophysiology of the condition. Regarding alterations in the classical and lectin-dependent complement systems, C3a, C3c, C4, and C5b-9 have been suggested to hold potential diagnostic value in endometriosis. Alternative pathway is another way for complement activation. This study aimed to investigate whether there are alterations in the levels of alternative complement molecules in both the blood serum and peritoneal fluid of patients diagnosed with endometriosis, comparing these levels to those found in healthy individuals. The research focused on understanding potential differences that could contribute to the pathophysiology of endometriosis, aiming to provide insights into the role of the alternative complement pathway in this gynecological condition.'},
  'conditionsModule': {'conditions': ['Endometriosis',
    'Complement System',
    'Alternative Complement Pathway']},
  'designModule': {'studyType': 'OBSERVATIONAL',
   'patientRegistry': False,
   'designInfo': {'observationalModel': 'CASE_CONTROL',
    'timePerspective': 'PROSPECTIVE'},
   'bioSpec': {'retention': 'SAMPLES_WITHOUT_DNA',
    'description': 'Serum samples were collected via antecubital venous blood sampling. In the study group, serum samples were obtained just before laparoscopy, while peritoneal fluid (PF) samples were collected from the Douglas pouch at the time of trochar insertion into the abdominal cavity. Serum and PF MASP-3, adipsin, properdin, and CFH levels were evaluated.'},
   'enrollmentInfo': {'count': 58, 'type': 'ACTUAL'}},
  'armsInterventionsModule': {'armGroups': [{'label': 'Endometriosis group (Study group)',
     'description': '* The study group included 32 women with endometriosis.\n* The study group consisted of women diagnosed with endometriosis who consecutively underwent laparoscopic endometriosis surgery.',
     'interventionNames': ['Diagnostic Test: Mannose-binding lectin-associated serine protease-3 (MASP-3) Level',
      'Diagnostic Test: Adipsin Level',
      'Diagnostic Test: Properdin Level',
      'Diagnostic Test: Complement Factor H (CFH) Level',
      'Diagnostic Test: Cancer Antigen 125 (CA-125) Level']},
    {'label': 'Healthy women (Control group)',
     'description': '* Control group consisted of 26 healthy women.\n* The control group consisted of women who consecutively visited the outpatient clinic for routine gynecologic examinations and had no known diseases.',
     'interventionNames': ['Diagnostic Test: Mannose-binding lectin-associated serine protease-3 (MASP-3) Level',
      'Diagnostic Test: Adipsin Level',
      'Diagnostic Test: Properdin Level',
      'Diagnostic Test: Complement Factor H (CFH) Level',
      'Diagnostic Test: Cancer Antigen 125 (CA-125) Level']}],
   'interventions': [{'type': 'DIAGNOSTIC_TEST',
     'name': 'Mannose-binding lectin-associated serine protease-3 (MASP-3) Level',
     'description': 'Measurement of venous blood serum and peritoneal fluid levels of MASP-3 level by ELISA method.',
     'armGroupLabels': ['Endometriosis group (Study group)',
      'Healthy women (Control group)']},
    {'type': 'DIAGNOSTIC_TEST',
     'name': 'Adipsin Level',
     'description': 'Measurement of venous blood serum and peritoneal fluid levels of adipsin level by ELISA method.',
     'armGroupLabels': ['Endometriosis group (Study group)',
      'Healthy women (Control group)']},
    {'type': 'DIAGNOSTIC_TEST',
     'name': 'Properdin Level',
     'description': 'Measurement of venous blood serum and peritoneal fluid levels of properdin level by ELISA method.',
     'armGroupLabels': ['Endometriosis group (Study group)',
      'Healthy women (Control group)']},
    {'type': 'DIAGNOSTIC_TEST',
     'name': 'Complement Factor H (CFH) Level',
     'description': 'Measurement of venous blood serum and peritoneal fluid levels of CFH level by ELISA method.',
     'armGroupLabels': ['Endometriosis group (Study group)',
      'Healthy women (Control group)']},
    {'type': 'DIAGNOSTIC_TEST',
     'name': 'Cancer Antigen 125 (CA-125) Level',
     'description': 'Measurement of venous blood serum level of CA-125 level by ELISA method.',
     'armGroupLabels': ['Endometriosis group (Study group)',
      'Healthy women (Control group)']}]},
  'outcomesModule': {'primaryOutcomes': [{'measure': 'Serum and peritoneal fluid mannose-binding lectin-associated serine protease-3 level',
     'description': 'Nanogram/milliliter',
     'timeFrame': 'day 1'},
    {'measure': 'Serum and peritoneal fluid adipsin level',
     'description': 'Nanogram/milliliter',
     'timeFrame': 'day 1'},
    {'measure': 'Serum and peritoneal fluid properdin level',
     'description': 'Nanogram/milliliter',
     'timeFrame': 'day 1'},
    {'measure': 'Serum and peritoneal fluid complement factor H level',
     'description': 'Nanogram/milliliter',
     'timeFrame': 'day 1'}],
   'secondaryOutcomes': [{'measure': 'Serum cancer antigen 125 level',
     'description': 'Unit/milliliter',
     'timeFrame': 'day 1'}]},
  'eligibilityModule': {'eligibilityCriteria': "Inclusion Criteria:\n\n* Diagnosis of endometriosis for study group who underwent laparoscopic endometriosis surgery\n* Healthy women for control group\n\nExclusion Criteria:\n\n* Cardiovascular diseases including hypertension\n* Type 1 or type 2 diabetes mellitus\n* Morbid obesity\n* Primary adrenal insufficiency\n* Uterine fibroids\n* Thyroid dysfunctions including Hashimoto thyroiditis and Grave's disease\n* Hepatic dysfunctions\n* Renal insufficiency\n* Genetic disorders in chromosome constitution or karyotype analysis including monosomy X, trisomy X and gene mutations as BMP15, FMR I, POFIB, and GDF9\n* Neurologic diseases\n* Psychiatric disorders\n* Autoimmune diseases or syndromes including Addison's disease, autoimmune syndromes, scleroderma, Sjogren's syndrome, myasthenia gravis, inflammatory bowel diseases, multiple sclerosis, rheumatoid arthritis, systemic lupus erythematosus and familial Mediterranean fever\n* History of any malignancy\n* History of exposure to chemotherapeutic agents or radiotherapy",
   'healthyVolunteers': True,
   'sex': 'FEMALE',
   'genderBased': True,
   'genderDescription': 'Endometriosis is the presence of endometrial tissue outside the uterus, such as in the ovaries, fallopian tubes, peritoneal membrane, or abdominal cavity, and it is diagnosed exclusively in females.',
   'minimumAge': '18 Years',
   'maximumAge': '44 Years',
   'stdAges': ['ADULT'],
   'studyPopulation': 'Study population includes a total of 58 participants. The study group consists of 32 women with the diagnosis of endometriosis, and the control group consists of 26 healthy women.',
   'samplingMethod': 'NON_PROBABILITY_SAMPLE'},
  'contactsLocationsModule': {'overallOfficials': [{'name': 'Merve Didem Eşkin Tanrıverdi, MD',
     'affiliation': 'Ankara City Hospital Bilkent',
     'role': 'PRINCIPAL_INVESTIGATOR'}],
   'locations': [{'facility': 'Ankara Bilkent City Hospital',
     'city': 'Ankara',
     'zip': '06100',
     'country': 'Turkey (Türkiye)',
     'geoPoint': {'lat': 39.91987, 'lon': 32.85427}}]},
  'referencesModule': {'references': [{'pmid': '29420391',
     'type': 'BACKGROUND',
     'citation': 'Falcone T, Flyckt R. Clinical Management of Endometriosis. Obstet Gynecol. 2018 Mar;131(3):557-571. doi: 10.1097/AOG.0000000000002469.'},
    {'pmid': '31488888',
     'type': 'BACKGROUND',
     'citation': 'Chapron C, Marcellin L, Borghese B, Santulli P. Rethinking mechanisms, diagnosis and management of endometriosis. Nat Rev Endocrinol. 2019 Nov;15(11):666-682. doi: 10.1038/s41574-019-0245-z. Epub 2019 Sep 5.'},
    {'pmid': '32325082',
     'type': 'BACKGROUND',
     'citation': 'Karadadas E, Hortu I, Ak H, Ergenoglu AM, Karadadas N, Aydin HH. Evaluation of complement system proteins C3a, C5a and C6 in patients of endometriosis. Clin Biochem. 2020 Jul;81:15-19. doi: 10.1016/j.clinbiochem.2020.04.005. Epub 2020 Apr 20.'},
    {'pmid': '17482181',
     'type': 'BACKGROUND',
     'citation': 'Kabut J, Kondera-Anasz Z, Sikora J, Mielczarek-Palacz A. Levels of complement components iC3b, C3c, C4, and SC5b-9 in peritoneal fluid and serum of infertile women with endometriosis. Fertil Steril. 2007 Nov;88(5):1298-303. doi: 10.1016/j.fertnstert.2006.12.061. Epub 2007 May 4.'},
    {'pmid': '11724962',
     'type': 'BACKGROUND',
     'citation': 'Xu Y, Ma M, Ippolito GC, Schroeder HW Jr, Carroll MC, Volanakis JE. Complement activation in factor D-deficient mice. Proc Natl Acad Sci U S A. 2001 Dec 4;98(25):14577-82. doi: 10.1073/pnas.261428398. Epub 2001 Nov 27.'},
    {'pmid': '20720586',
     'type': 'BACKGROUND',
     'citation': 'Ricklin D, Hajishengallis G, Yang K, Lambris JD. Complement: a key system for immune surveillance and homeostasis. Nat Immunol. 2010 Sep;11(9):785-97. doi: 10.1038/ni.1923. Epub 2010 Aug 19.'},
    {'pmid': '34682837',
     'type': 'BACKGROUND',
     'citation': 'Poppelaars F, Faria B, Schwaeble W, Daha MR. The Contribution of Complement to the Pathogenesis of IgA Nephropathy: Are Complement-Targeted Therapies Moving from Rare Disorders to More Common Diseases? J Clin Med. 2021 Oct 14;10(20):4715. doi: 10.3390/jcm10204715.'},
    {'pmid': '34671343',
     'type': 'BACKGROUND',
     'citation': 'Liu M, Luo X, Xu Q, Yu H, Gao L, Zhou R, Wang T. Adipsin of the Alternative Complement Pathway Is a Potential Predictor for Preeclampsia in Early Pregnancy. Front Immunol. 2021 Oct 4;12:702385. doi: 10.3389/fimmu.2021.702385. eCollection 2021.'},
    {'pmid': '27434652',
     'type': 'BACKGROUND',
     'citation': 'Gursoy Calan O, Calan M, Yesil Senses P, Unal Kocabas G, Ozden E, Sari KR, Kocar M, Imamoglu C, Senses YM, Bozkaya G, Bilgir O. Increased adipsin is associated with carotid intima media thickness and metabolic disturbances in polycystic ovary syndrome. Clin Endocrinol (Oxf). 2016 Dec;85(6):910-917. doi: 10.1111/cen.13157. Epub 2016 Aug 15.'},
    {'pmid': '34696714',
     'type': 'BACKGROUND',
     'citation': 'Zhang J, Teng F, Pan L, Guo D, Liu J, Li K, Yuan Y, Li W, Zhang H. Circulating adipsin is associated with asymptomatic carotid atherosclerosis in obese adults. BMC Cardiovasc Disord. 2021 Oct 25;21(1):517. doi: 10.1186/s12872-021-02329-3.'},
    {'pmid': '34566967',
     'type': 'BACKGROUND',
     'citation': 'Barratt J, Weitz I. Complement Factor D as a Strategic Target for Regulating the Alternative Complement Pathway. Front Immunol. 2021 Sep 9;12:712572. doi: 10.3389/fimmu.2021.712572. eCollection 2021.'},
    {'pmid': '38145036',
     'type': 'BACKGROUND',
     'citation': 'Lei X, Song X, Fan Y, Chen Z, Zhang L. The Role and Potential Mechanism of Complement Factor D in Fibromyalgia Development. J Pain Res. 2023 Dec 19;16:4337-4351. doi: 10.2147/JPR.S439689. eCollection 2023.'},
    {'pmid': '33505394',
     'type': 'BACKGROUND',
     'citation': 'Agostinis C, Balduit A, Mangogna A, Zito G, Romano F, Ricci G, Kishore U, Bulla R. Immunological Basis of the Endometriosis: The Complement System as a Potential Therapeutic Target. Front Immunol. 2021 Jan 11;11:599117. doi: 10.3389/fimmu.2020.599117. eCollection 2020.'},
    {'pmid': '37108664',
     'type': 'BACKGROUND',
     'citation': 'Chen LH, Lo WC, Huang HY, Wu HM. A Lifelong Impact on Endometriosis: Pathophysiology and Pharmacological Treatment. Int J Mol Sci. 2023 Apr 19;24(8):7503. doi: 10.3390/ijms24087503.'},
    {'pmid': '27782323',
     'type': 'BACKGROUND',
     'citation': 'Garred P, Genster N, Pilely K, Bayarri-Olmos R, Rosbjerg A, Ma YJ, Skjoedt MO. A journey through the lectin pathway of complement-MBL and beyond. Immunol Rev. 2016 Nov;274(1):74-97. doi: 10.1111/imr.12468.'}]},
  'ipdSharingStatementModule': {'ipdSharing': 'NO',
   'description': 'IPD are available which may be shared in necessary conditions.'}},
 'derivedSection': {'miscInfoModule': {'versionHolder': '2026-08-11'},
  'conditionBrowseModule': {'meshes': [{'id': 'D004715',
     'term': 'Endometriosis'}],
   'ancestors': [{'id': 'D005831', 'term': 'Genital Diseases, Female'},
    {'id': 'D052776', 'term': 'Female Urogenital Diseases'},
    {'id': 'D005261',
     'term': 'Female Urogenital Diseases and Pregnancy Complications'},
    {'id': 'D000091642', 'term': 'Urogenital Diseases'},
    {'id': 'D000091662', 'term': 'Genital Diseases'}]}},
 'hasResults': False}

In [18]:
protocol = first_study["protocolSection"]

protocol.keys()

dict_keys(['identificationModule', 'statusModule', 'sponsorCollaboratorsModule', 'oversightModule', 'descriptionModule', 'conditionsModule', 'designModule', 'armsInterventionsModule', 'outcomesModule', 'eligibilityModule', 'contactsLocationsModule', 'referencesModule', 'ipdSharingStatementModule'])

In [19]:
identification = protocol["identificationModule"]

print("NCT ID:", identification["nctId"])
print("Title:", identification["briefTitle"])

NCT ID: NCT06495151
Title: Endometriosis and Complement System

In [20]:
conditions = protocol.get("conditionsModule", {}).get("conditions", [])

conditions

['Endometriosis', 'Complement System', 'Alternative Complement Pathway']

In [21]:
def extract_study_info(study, searched_condition):
    """Extract useful fields from one ClinicalTrials.gov study."""

    protocol = study.get("protocolSection", {})

    identification = protocol.get("identificationModule", {})
    status = protocol.get("statusModule", {})
    design = protocol.get("designModule", {})
    conditions = protocol.get("conditionsModule", {})
    sponsors = protocol.get("sponsorCollaboratorsModule", {})
    eligibility = protocol.get("eligibilityModule", {})

    enrollment_info = design.get("enrollmentInfo", {})
    lead_sponsor = sponsors.get("leadSponsor", {})

    start_date_info = status.get("startDateStruct", {})
    completion_date_info = status.get("completionDateStruct", {})

    return {
        "nct_id": identification.get("nctId"),
        "searched_condition": searched_condition,
        "brief_title": identification.get("briefTitle"),
        "official_title": identification.get("officialTitle"),
        "listed_conditions": conditions.get("conditions", []),
        "study_type": design.get("studyType"),
        "phases": design.get("phases", []),
        "overall_status": status.get("overallStatus"),
        "start_date": start_date_info.get("date"),
        "completion_date": completion_date_info.get("date"),
        "enrollment": enrollment_info.get("count"),
        "enrollment_type": enrollment_info.get("type"),
        "lead_sponsor": lead_sponsor.get("name"),
        "sponsor_class": lead_sponsor.get("class"),
        "sex": eligibility.get("sex"),
        "minimum_age": eligibility.get("minimumAge"),
        "maximum_age": eligibility.get("maximumAge"),
        "has_results": study.get("hasResults", False),
    }

In [22]:
records = [
    extract_study_info(
        study=study,
        searched_condition="Endometriosis"
    )
    for study in data["studies"]
]

sample_df = pd.DataFrame(records)

sample_df

,nct_id,searched_condition,brief_title,official_title,listed_conditions,study_type,phases,overall_status,start_date,completion_date,enrollment,enrollment_type,lead_sponsor,sponsor_class,sex,minimum_age,maximum_age,has_results
0,NCT06495151,Endometriosis,Endometriosis and Complement System,Evaluation of Serum and Peritoneal Fluid Manno...,"[Endometriosis, Complement System, Alternative...",OBSERVATIONAL,[],COMPLETED,2022-06-10,2022-10-07,58,ACTUAL,Ankara City Hospital Bilkent,OTHER,FEMALE,18 Years,44 Years,False
1,NCT05312528,Endometriosis,Evaluation of New Biomarkers in Stage 3 and 4 ...,"Diagnostic Value of Annexin V, sVCAM-1, sICAM-...",[Endometriosis],OBSERVATIONAL,[],COMPLETED,2018-02-01,2019-03-01,79,ACTUAL,Bagcilar Training and Research Hospital,OTHER_GOV,FEMALE,18 Years,50 Years,False
2,NCT07664956,Endometriosis,Cyclobenzaprine for Postoperative Pain in Mini...,Cyclobenzaprine for Postoperative Pain in Mini...,"[Minimally Invasive Surgical Procedures, Abnor...",INTERVENTIONAL,[PHASE4],NOT_YET_RECRUITING,2026-07-01,2026-12-01,36,ESTIMATED,Christiana Care Health Services,OTHER,FEMALE,18 Years,None,False
3,NCT04265781,Endometriosis,Study on the Safety of Drug BAY1817080 at Diff...,Phase 1 Dose Escalation Study to Investigate S...,"[Endometriosis Related Pain, Overactive Bladde...",INTERVENTIONAL,[PHASE1],COMPLETED,2020-02-15,2020-09-20,36,ACTUAL,Bayer,INDUSTRY,MALE,20 Years,45 Years,False
4,NCT07241637,Endometriosis,"Effect of Tele-Yoga on Pain, Fatigue, and Qual...",The Effect of Tele-Yoga Application on Chronic...,"[Pelvic Pain, Endometriosis]",INTERVENTIONAL,[NA],COMPLETED,2025-09-01,2026-06-30,60,ACTUAL,Ankara University,OTHER,FEMALE,18 Years,65 Years,False

In [23]:
sample_df[
    [
        "nct_id",
        "searched_condition",
        "study_type",
        "overall_status",
        "enrollment",
        "sponsor_class",
        "has_results",
    ]
]

,nct_id,searched_condition,study_type,overall_status,enrollment,sponsor_class,has_results
0,NCT06495151,Endometriosis,OBSERVATIONAL,COMPLETED,58,OTHER,False
1,NCT05312528,Endometriosis,OBSERVATIONAL,COMPLETED,79,OTHER_GOV,False
2,NCT07664956,Endometriosis,INTERVENTIONAL,NOT_YET_RECRUITING,36,OTHER,False
3,NCT04265781,Endometriosis,INTERVENTIONAL,COMPLETED,36,INDUSTRY,False
4,NCT07241637,Endometriosis,INTERVENTIONAL,COMPLETED,60,OTHER,False

In [24]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   nct_id              5 non-null      object
 1   searched_condition  5 non-null      object
 2   brief_title         5 non-null      object
 3   official_title      5 non-null      object
 4   listed_conditions   5 non-null      object
 5   study_type          5 non-null      object
 6   phases              5 non-null      object
 7   overall_status      5 non-null      object
 8   start_date          5 non-null      object
 9   completion_date     5 non-null      object
 10  enrollment          5 non-null      int64
 11  enrollment_type     5 non-null      object
 12  lead_sponsor        5 non-null      object
 13  sponsor_class       5 non-null      object
 14  sex                 5 non-null      object
 15  minimum_age         5 non-null      object
 16  maximum_age         4 non-null      object
 17  has_results         5 non-null      bool
dtypes: bool(1), int64(1), object(16)
memory usage: 813.0+ bytes

In [25]:
sample_df.isna().sum()

nct_id                0
searched_condition    0
brief_title           0
official_title        0
listed_conditions     0
study_type            0
phases                0
overall_status        0
start_date            0
completion_date       0
enrollment            0
enrollment_type       0
lead_sponsor          0
sponsor_class         0
sex                   0
minimum_age           0
maximum_age           1
has_results           0
dtype: int64

In [26]:
sample_df.to_csv(
    "../data/raw/endometriosis_sample.csv",
    index=False
)

In [27]:
API_URL = "https://clinicaltrials.gov/api/v2/studies"


def fetch_study_page(condition, page_size=100, page_token=None):
    """Retrieve one page of ClinicalTrials.gov studies."""

    params = {
        "query.cond": condition,
        "pageSize": page_size,
        "format": "json",
    }

    if page_token is not None:
        params["pageToken"] = page_token

    response = requests.get(
        API_URL,
        params=params,
        timeout=30
    )

    response.raise_for_status()

    return response.json()

In [28]:
test_page = fetch_study_page(
    condition="Endometriosis",
    page_size=10
)

len(test_page["studies"])

10

In [29]:
def fetch_all_studies(condition, page_size=100, max_pages=None):
    """Retrieve all available studies for one condition."""

    all_studies = []
    page_token = None
    page_number = 0

    while True:
        page_data = fetch_study_page(
            condition=condition,
            page_size=page_size,
            page_token=page_token
        )

        studies = page_data.get("studies", [])
        all_studies.extend(studies)

        page_number += 1

        print(
            f"{condition}: downloaded page {page_number}, "
            f"total studies = {len(all_studies)}"
        )

        page_token = page_data.get("nextPageToken")

        if not page_token:
            break

        if max_pages is not None and page_number >= max_pages:
            break

    return all_studies

In [30]:
endometriosis_test = fetch_all_studies(
    condition="Endometriosis",
    page_size=100,
    max_pages=2
)

Endometriosis: downloaded page 1, total studies = 100
Endometriosis: downloaded page 2, total studies = 200

In [31]:
len(endometriosis_test)

200

In [32]:
endometriosis_records = [
    extract_study_info(
        study=study,
        searched_condition="Endometriosis"
    )
    for study in endometriosis_test
]

endometriosis_df = pd.DataFrame(endometriosis_records)

endometriosis_df.head()

,nct_id,searched_condition,brief_title,official_title,listed_conditions,study_type,phases,overall_status,start_date,completion_date,enrollment,enrollment_type,lead_sponsor,sponsor_class,sex,minimum_age,maximum_age,has_results
0,NCT06495151,Endometriosis,Endometriosis and Complement System,Evaluation of Serum and Peritoneal Fluid Manno...,"[Endometriosis, Complement System, Alternative...",OBSERVATIONAL,[],COMPLETED,2022-06-10,2022-10-07,58.0,ACTUAL,Ankara City Hospital Bilkent,OTHER,FEMALE,18 Years,44 Years,False
1,NCT05312528,Endometriosis,Evaluation of New Biomarkers in Stage 3 and 4 ...,"Diagnostic Value of Annexin V, sVCAM-1, sICAM-...",[Endometriosis],OBSERVATIONAL,[],COMPLETED,2018-02-01,2019-03-01,79.0,ACTUAL,Bagcilar Training and Research Hospital,OTHER_GOV,FEMALE,18 Years,50 Years,False
2,NCT07664956,Endometriosis,Cyclobenzaprine for Postoperative Pain in Mini...,Cyclobenzaprine for Postoperative Pain in Mini...,"[Minimally Invasive Surgical Procedures, Abnor...",INTERVENTIONAL,[PHASE4],NOT_YET_RECRUITING,2026-07-01,2026-12-01,36.0,ESTIMATED,Christiana Care Health Services,OTHER,FEMALE,18 Years,None,False
3,NCT04265781,Endometriosis,Study on the Safety of Drug BAY1817080 at Diff...,Phase 1 Dose Escalation Study to Investigate S...,"[Endometriosis Related Pain, Overactive Bladde...",INTERVENTIONAL,[PHASE1],COMPLETED,2020-02-15,2020-09-20,36.0,ACTUAL,Bayer,INDUSTRY,MALE,20 Years,45 Years,False
4,NCT07241637,Endometriosis,"Effect of Tele-Yoga on Pain, Fatigue, and Qual...",The Effect of Tele-Yoga Application on Chronic...,"[Pelvic Pain, Endometriosis]",INTERVENTIONAL,[NA],COMPLETED,2025-09-01,2026-06-30,60.0,ACTUAL,Ankara University,OTHER,FEMALE,18 Years,65 Years,False

In [33]:
endometriosis_df.shape

(200, 18)

In [34]:
endometriosis_df["nct_id"].duplicated().sum()

np.int64(0)

In [35]:
endometriosis_df["overall_status"].value_counts()

overall_status
COMPLETED                  96
RECRUITING                 36
UNKNOWN                    34
NOT_YET_RECRUITING         14
TERMINATED                  7
ACTIVE_NOT_RECRUITING       7
WITHDRAWN                   3
ENROLLING_BY_INVITATION     2
SUSPENDED                   1
Name: count, dtype: int64

In [36]:
endometriosis_df["study_type"].value_counts()

study_type
INTERVENTIONAL    122
OBSERVATIONAL      78
Name: count, dtype: int64

In [37]:
endometriosis_df["enrollment"].describe()

count     197.000000
mean      255.284264
std       887.896666
min         0.000000
25%        43.000000
50%        86.000000
75%       180.000000
max      9979.000000
Name: enrollment, dtype: float64

In [38]:
endometriosis_df.to_csv(
    "../data/raw/endometriosis_test.csv",
    index=False
)